name: End to End challenge
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test

  build:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set environment
        run: echo "owner_lc=${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
#          tags: ghcr.io/${{ github.repository | downcase }}/app:latest
          tags: ${{ github.repository_owner }}/github-actions-basics/app:latest
#          tags: ghcr.io/${{ github.repository }}/app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying application..."
          echo "Restarting server..."

